In [14]:
import regex as re
import pandas as pd
import os
import random
import numpy as np


In [15]:
data = pd.read_csv('smalldata_washed.csv')
rumor = data['rumor'].to_list()
reverse = data['reverse'].to_list()
rumor_class = len(rumor)*[1]
reverse_class = len(reverse)*[0]
data = rumor + reverse
data_class = rumor_class + reverse_class


In [16]:
#后续添加数据要放在raw目录下，使用.xlsx格式将后续标注的数据加入data
raw_data_list = os.listdir('raw')
data_list = []
good_name = re.compile(r'^(?!(\~\$)).*(.xlsx)')
for i in raw_data_list:
    if good_name.match(i):
    #    data_list.append(i)
        temp = pd.read_excel('raw/'+i)
        temp.fillna('',inplace=True)
        temp_rumor = [x.strip() for x in  temp['谣言'].to_list()  if x.strip()!='']
        temp_reverse = [x.strip() for x in  temp['真相'].to_list()  if x.strip()!='']
        temp_rumor_class = len(temp_rumor)*[1]
        temp_reverse_class = len(temp_reverse)*[0]
        temp_data = temp_rumor + temp_reverse
        temp_data_class = temp_rumor_class + temp_reverse_class
        for i in range( len(temp_data)):
            temp_data[i]=re.sub(r'[\,\'\ ]|(\n)','',temp_data[i])
    data = data + temp_data
    data_class = data_class + temp_data_class
with open('data.txt','w') as f:
    for i in range(len(data)):
        f.write(data[i]+'\t'+str(data_class[i])+'\n')

In [17]:
data_list =list( zip(data, data_class))
random.shuffle(data_list)
data, data_class = zip(*data_list)
index = ['rumor{}{}'.format(i, '!' * j) for (i, j) in zip(range(len(data)), data_class)]
df = pd .DataFrame(data=zip(data_class,data), columns=["rumor","text"], index=index)

In [18]:
# jieba分词
import jieba
for i in range(len(df)):
    df["text"].iloc[i] = ' '.join(jieba.cut(df["text"].iloc[i],cut_all=False)) 

/var/folders/f0/6j6j3w814n53skbt2s4d8p5m0000gn/T/ipykernel_61768/1898959079.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text"].iloc[i] = ' '.join(jieba.cut(df["text"].iloc[i],cut_all=False))


#### 使用sklearn计算TF-IDF

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize.casual import casual_tokenize

In [20]:
tfidf_model = TfidfVectorizer(tokenizer=casual_tokenize)
tfidf_docs = tfidf_model.fit_transform(raw_documents=df.text).toarray()#这句话计算了tfidf
tfidf_docs.shape

/Users/stevenyu/opt/anaconda3/envs/nlpiaenv/lib/python3.9/site-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


(798, 4248)

In [21]:
df.rumor.sum()

330

#### 使用LDA语义分析技术进行聚类

In [22]:
msak = df.rumor.astype(bool).values
spam_centroid = tfidf_docs[msak].mean(axis=0)
ham_centroid = tfidf_docs[~msak].mean(axis=0)
spam_centroid.round(2)



array([0., 0., 0., ..., 0., 0., 0.])

In [23]:
ham_centroid.round(2)

array([0., 0., 0., ..., 0., 0., 0.])

In [24]:
spamminess_score = tfidf_docs.dot(spam_centroid - ham_centroid)
spamminess_score.round(2)

array([-0.02, -0.03, -0.03,  0.01, -0.01,  0.  , -0.  , -0.03, -0.01,
        0.  , -0.03, -0.03, -0.02,  0.01, -0.01,  0.01, -0.02, -0.03,
       -0.03, -0.02, -0.03, -0.  , -0.03, -0.01, -0.02, -0.04, -0.01,
       -0.01, -0.02, -0.01, -0.04, -0.03, -0.04, -0.01, -0.02, -0.  ,
        0.01, -0.03, -0.03, -0.04, -0.02, -0.01, -0.04, -0.01,  0.  ,
       -0.01, -0.02, -0.06, -0.04, -0.  , -0.03,  0.  , -0.02, -0.03,
        0.01, -0.03, -0.03, -0.02, -0.02,  0.01, -0.02, -0.  ,  0.  ,
       -0.04, -0.01, -0.04, -0.04, -0.  , -0.02, -0.01, -0.  , -0.02,
       -0.03,  0.01, -0.04,  0.  , -0.03, -0.02, -0.01, -0.03, -0.02,
       -0.01, -0.  , -0.  ,  0.01,  0.  , -0.02,  0.  , -0.02, -0.  ,
       -0.01, -0.01, -0.04, -0.03, -0.01, -0.04, -0.02, -0.05, -0.02,
        0.  , -0.  , -0.02, -0.  , -0.01, -0.03, -0.03, -0.04, -0.04,
        0.  , -0.03, -0.03, -0.02, -0.  ,  0.  , -0.04, -0.  ,  0.01,
       -0.02, -0.03, -0.04, -0.02,  0.01,  0.  ,  0.  , -0.04,  0.01,
       -0.01, -0.03,

In [25]:
from sklearn.preprocessing import MinMaxScaler
df['lda_score'] = MinMaxScaler().fit_transform(spamminess_score.reshape(-1, 1))
df['lda_pred'] = (df.lda_score > .5).astype(int)
df['rumor lda_pred lda_score'.split()].round(2).head(6)

rumor  lda_pred  lda_score
rumor0       0         0       0.49
rumor1       0         0       0.37
rumor2       0         0       0.46
rumor3!      1         1       0.88
rumor4       0         1       0.72
rumor5!      1         1       0.81

In [26]:
(1. - (df.rumor - df.lda_pred).abs().sum() / len(df)).round(4)

0.807